package me.corriekay.pokegoutil.utils.pokemon;

import java.util.List;

import com.pokegoapi.api.pokemon.Pokemon;
import com.pokegoapi.main.PokemonMeta;

import POGOProtos.Enums.PokemonIdOuterClass.PokemonId;
import POGOProtos.Enums.PokemonMoveOuterClass.PokemonMove;
import POGOProtos.Settings.Master.MoveSettingsOuterClass.MoveSettings;
import POGOProtos.Settings.Master.PokemonSettingsOuterClass.PokemonSettings;
import POGOProtos.Settings.Master.Pokemon.StatsAttributesOuterClass.StatsAttributes;
import me.corriekay.pokegoutil.utils.ConfigKey;
import me.corriekay.pokegoutil.utils.ConfigNew;
import me.corriekay.pokegoutil.utils.Utilities;


import me.corriekay.pokegoutil.data.managers.ProfileManager;
import com.pokegoapi.api.player.PlayerProfile;

import me.corriekay.pokegoutil.windows.PokemonGoMainWindow;

import me.corriekay.pokegoutil.utils.pokemon.PokemonUtils;


// every new move change by Niantic we need to look here (of another site) and then update the arrays
// http://heavy.com/games/2016/07/pokemon-go-move-guide-tier-list-best-moves-each-type-species-ranking-dps-damage-per-second/
// http://heavy.com/games/2017/02/pokemon-go-move-guide-best-moves-set-sets-generation-two-each-species-list/


/**
 * A Utility class providing several methods to calculate stats and values of Pokémon.
 * Most important ivRating, Duel Ability, Gym Offense and Defense.
 */
public final class PokemonMovesetUtils 
{

 static String[] Moveset_PokemonNames;
 static String[] Moveset_OffsensiveMoves1;
 static String[] Moveset_OffsensiveMoves2;
 static String[] Moveset_DefensiveMoves1;
 static String[] Moveset_DefensiveMoves2;

  static {
    Moveset_PokemonNames = new String[] {
new String("null"),
new String("Bulbasaur"),
new String("Ivysaur"),
new String("Venusaur"),
new String("Charmander"),
new String("Charmeleon"),
new String("Charizard"),
new String("Squirtle"),
new String("Wartortle"),
new String("Blastoise"),
new String("Caterpie"),
new String("Metapod"),
new String("Butterfree"),
new String("Weedle"),
new String("Kakuna"),
new String("Beedrill"),
new String("Pidgey"),
new String("Pidgeotto"),
new String("Pidgeot"),
new String("Rattata"),
new String("Raticate"),
new String("Spearow"),
new String("Fearow"),
new String("Ekans"),
new String("Arbok"),
new String("Pikachu"),
new String("Raichu"),
new String("Sandshrew"),
new String("Sandslash"),
new String("Nidoran (Female)"),
new String("Nidorina"),
new String("Nidoqueen"),
new String("Nidoran (Male)"),
new String("Nidorino"),
new String("Nidoking"),
new String("Clefairy"),
new String("Clefable"),
new String("Vulpix"),
new String("Ninetales"),
new String("Jigglypuff"),
new String("Wigglytuff"),
new String("Zubat"),
new String("Golbat"),
new String("Oddish"),
new String("Gloom"),
new String("Vileplume"),
new String("Paras"),
new String("Parasect"),
new String("Venonat"),
new String("Venomoth"),
new String("Diglett"),
new String("Dugtrio"),
new String("Meowth"),
new String("Persian"),
new String("Psyduck"),
new String("Golduck"),
new String("Mankey"),
new String("Primeape"),
new String("Growlithe"),
new String("Arcanine"),
new String("Poliwag"),
new String("Poliwhirl"),
new String("Poliwrath"),
new String("Abra"),
new String("Kadabra"),
new String("Alakazam"),
new String("Machop"),
new String("Machoke"),
new String("Machamp"),
new String("Bellsprout"),
new String("Weepinbell"),
new String("Victreebel"),
new String("Tentacool"),
new String("Tentacruel"),
new String("Geodude"),
new String("Graveler"),
new String("Golem"),
new String("Ponyta"),
new String("Rapidash"),
new String("Slowpoke"),
new String("Slowbro"),
new String("Magnemite"),
new String("Magneton"),
new String("Farfetch’d"),
new String("Doduo"),
new String("Dodrio"),
new String("Seel"),
new String("Dewgong"),
new String("Grimer"),
new String("Muk"),
new String("Shellder"),
new String("Cloyster"),
new String("Gastly"),
new String("Haunter"),
new String("Gengar"),
new String("Onix"),
new String("Drowzee"),
new String("Hypno"),
new String("Krabby"),
new String("Kingler"),
new String("Voltorb"),
new String("Electrode"),
new String("Exeggcute"),
new String("Exeggutor"),
new String("Cubone"),
new String("Marowak"),
new String("Hitmonlee"),
new String("Hitmonchan"),
new String("Lickitung"),
new String("Koffing"),
new String("Weezing"),
new String("Rhyhorn"),
new String("Rhydon"),
new String("Chansey"),
new String("Tangela"),
new String("Kangaskhan"),
new String("Horsea"),
new String("Seadra"),
new String("Goldeen"),
new String("Seaking"),
new String("Staryu"),
new String("Starmie"),
new String("Mr. Mime"),
new String("Scyther"),
new String("Jynx"),
new String("Electabuzz"),
new String("Magmar"),
new String("Pinsir"),
new String("Tauros"),
new String("Magikarp"),
new String("Gyarados"),
new String("Lapras"),
new String("Eevee"),
new String("Vaporeon"),
new String("Jolteon"),
new String("Flareon"),
new String("Porygon"),
new String("Omanyte"),
new String("Omastar"),
new String("Kabuto"),
new String("Kabutops"),
new String("Aerodactyl"),
new String("Snorlax"),
new String("Dratini"),
new String("Dragonair"),
new String("Dragonite"),
new String("Chikorita"),
new String("Bayleef"),
new String("Meganium"),
new String("Cyndaquil"),
new String("Quilava"),
new String("Typhlosion"),
new String("Totodile"),
new String("Croconaw"),
new String("Feraligatr"),
new String("Sentret"),
new String("Furret"),
new String("Hoothoot"),
new String("Noctowl"),
new String("Ledyba"),
new String("Ledian"),
new String("Spinarak"),
new String("Ariados"),
new String("Crobat"),
new String("Chinchou"),
new String("Lanturn"),
new String("Pichu"),
new String("Cleffa"),
new String("Igglybuff"),
new String("Togepi"),
new String("Togetic"),
new String("Natu"),
new String("Xatu"),
new String("Mareep"),
new String("Flaaffy"),
new String("Ampharos"),
new String("Bellossom"),
new String("Marill"),
new String("Azumarill"),
new String("Sudowoodo"),
new String("Politoed"),
new String("Hoppip"),
new String("Skiploom"),
new String("Jumpluff"),
new String("Aipom"),
new String("Sunkern"),
new String("Sunflora"),
new String("Yanma"),
new String("Wooper"),
new String("Quagsire"),
new String("Espeon"),
new String("Umbreon"),
new String("Murkrow"),
new String("Slowking"),
new String("Misdreavus"),
new String("Unown"),
new String("Wobbuffet"),
new String("Girafarig"),
new String("Pineco"),
new String("Forretress"),
new String("Dunsparce"),
new String("Gligar"),
new String("Steelix"),
new String("Snubbull"),
new String("Granbull"),
new String("Qwilfish"),
new String("Scizor"),
new String("Shuckle"),
new String("Heracross"),
new String("Sneasel"),
new String("Teddiursa"),
new String("Ursaring"),
new String("Slugma"),
new String("Magcargo"),
new String("Swinub"),
new String("Piloswine"),
new String("Corsola"),
new String("Remoraid"),
new String("Octillery"),
new String("Delibird"),
new String("Mantine"),
new String("Skarmory"),
new String("Houndour"),
new String("Houndoom"),
new String("Kingdra"),
new String("Phanpy"),
new String("Donphan"),
new String("Porygon2"),
new String("Stantler"),
new String("Smeargle"),
new String("Tyrogue"),
new String("Hitmontop"),
new String("Smoochum"),
new String("Elekid"),
new String("Magby"),
new String("Miltank"),
new String("Blissey"),
new String("Raikou"),
new String("Entei"),
new String("Suicune"),
new String("Larvitar"),
new String("Pupitar"),
new String("Tyranitar"),
new String("Lugia"),
new String("Ho-Oh"),
new String("Celebi")

};
}

  static {
    Moveset_OffsensiveMoves1 = new String[] {
new String("null"),
new String("Vine Whip"),
new String("Vine Whip"),
new String("Vine Whip"),
new String("Ember"),
new String("Fire Fang"),
new String("Fire Spin"),
new String("Bubble"),
new String("Water Gun"),
new String("Water Gun"),
new String("Bug Bite"),
new String("Bug Bite"),
new String("Struggle Bug"),
new String("Bug Bite"),
new String("Bug Bite"),
new String("Poison Jab"),
new String("Quick Attack"),
new String("Wing Attack"),
new String("Air Slash"),
new String("Quick Attack"),
new String("Quick Attack"),
new String("Quick Attack"),
new String("Peck"),
new String("Acid"),
new String("Acid"),
new String("Thunder Shock"),
new String("Mud Shot"),
new String("Mud Shot"),
new String("Metal Claw"),
new String("Poison Sting"),
new String("Poison Sting"),
new String("Poison Jab"),
new String("Poison Sting"),
new String("Poison Jab"),
new String("Poison Jab"),
new String("Pound"),
new String("Charge Beam"),
new String("Ember"),
new String("Fire Spin"),
new String("Pound"),
new String("Pound"),
new String("Quick Attack"),
new String("Wing Attack"),
new String("Razor Leaf"),
new String("Razor Leaf"),
new String("Acid"),
new String("Bug Bite"),
new String("Fury Cutter Bug"),
new String("Bug Bite"),
new String("Infestation"),
new String("Scratch"),
new String("Mud Slap"),
new String("Scratch"),
new String("Scratch"),
new String("Water Gun"),
new String("Water Gun"),
new String("Karate Chop"),
new String("Counter"),
new String("Ember"),
new String("Fire Fang"),
new String("Bubble"),
new String("Bubble"),
new String("Bubble"),
new String("Zen Headbutt"),
new String("Confusion"),
new String("Confusion"),
new String("Karate Chop"),
new String("Karate Chop"),
new String("Counter"),
new String("Vine Whip"),
new String("Acid"),
new String("Acid"),
new String("Bubble"),
new String("Poison Jab"),
new String("Rock Throw"),
new String("Rock Throw"),
new String("Rock Throw"),
new String("Ember"),
new String("Fire Spin"),
new String("Confusion"),
new String("Confusion"),
new String("Thunder Shock"),
new String("Spark"),
new String("Air Slash"),
new String("Quick Attack"),
new String("Steel Wing"),
new String("Lick"),
new String("Frost Breath"),
new String("Poison Jab"),
new String("Poison Jab"),
new String("Tackle"),
new String("Frost Breath"),
new String("Lick"),
new String("Shadow Claw"),
new String("Hex"),
new String("Rock Throw"),
new String("Confusion"),
new String("Confusion"),
new String("Bubble"),
new String("Bubble"),
new String("Spark"),
new String("Spark"),
new String("Confusion"),
new String("Extrasensory"),
new String("Mud Slap"),
new String("Mud Slap"),
new String("Rock Smash"),
new String("Counter"),
new String("Lick"),
new String("Infestation"),
new String("Infestation"),
new String("Mud Slap"),
new String("Mud Slap"),
new String("Pound"),
new String("Vine Whip"),
new String("Mud Slap"),
new String("Bubble"),
new String("Water Gun"),
new String("Peck"),
new String("Poison Jab"),
new String("Water Gun"),
new String("Water Gun"),
new String("Confusion"),
new String("Air Slash"),
new String("Confusion"),
new String("Thunder Shock"),
new String("Ember"),
new String("Bug Bite"),
new String("Tackle"),
new String("Splash"),
new String("Dragon Tail"),
new String("Water Gun"),
new String("Quick Attack"),
new String("Water Gun"),
new String("Thunder Shock"),
new String("Fire Spin"),
new String("Hidden Power"),
new String("Water Gun"),
new String("Water Gun"),
new String("Scratch"),
new String("Rock Smash"),
new String("Steel Wing"),
new String("Lick"),
new String("Dragon Breath"),
new String("Dragon Breath"),
new String("Steel Wing"),
new String("Vine Whip"),
new String("Razor Leaf"),
new String("Vine Whip"),
new String("Ember"),
new String("Ember"),
new String("Ember"),
new String("Water Gun"),
new String("Water Gun"),
new String("Water Gun"),
new String("Quick Attack"),
new String("Quick Attack"),
new String("Peck"),
new String("Wing Attack"),
new String("Bug Bite"),
new String("Bug Bite"),
new String("Bug Bite"),
new String("Infestation"),
new String("Air Slash"),
new String("Bubble"),
new String("Water Gun"),
new String("Thunder Shock"),
new String("Pound"),
new String("Pound"),
new String("Peck"),
new String("Extrasensory"),
new String("Peck"),
new String("Air Slash"),
new String("Thunder Shock"),
new String("Charge Beam"),
new String("Charge Beam"),
new String("Razor Leaf"),
new String("Bubble"),
new String("Bubble"),
new String("Rock Throw"),
new String("Bubble"),
new String("Bullet Seed"),
new String("Bullet Seed"),
new String("Infestation"),
new String("Scratch"),
new String("Razor Leaf"),
new String("Razor Leaf"),
new String("Wing Attack"),
new String("Water Gun"),
new String("Water Gun"),
new String("Confusion"),
new String("Snarl"),
new String("Feint Attack"),
new String("Confusion"),
new String("Hex"),
new String("Hidden Power"),
new String("Counter"),
new String("Confusion"),
new String("Bug Bite"),
new String("Bug Bite"),
new String("Bite"),
new String("Wing Attack"),
new String("Iron Tail"),
new String("Bite"),
new String("Snarl"),
new String("Water Gun"),
new String("Bullet Punch"),
new String("Rock Throw"),
new String("Counter"),
new String("Feint Attack"),
new String("Scratch"),
new String("Counter"),
new String("Ember"),
new String("Rock Throw"),
new String("Powder Snow"),
new String("Ice Shard"),
new String("Bubble"),
new String("Water Gun"),
new String("Water Gun"),
new String("Ice Shard"),
new String("Wing Attack"),
new String("Steel Wing"),
new String("Feint Attack"),
new String("Fire Fang"),
new String("Dragon Breath"),
new String("Tackle"),
new String("Counter"),
new String("Hidden Power"),
new String("Tackle"),
new String("Tackle"),
new String("Rock Smash"),
new String("Counter"),
new String("Powder Snow"),
new String("Thunder Shock"),
new String("Ember"),
new String("Tackle"),
new String("Pound"),
new String("Thunder Shock"),
new String("Fire Spin"),
new String("Extrasensory"),
new String("Bite"),
new String("Bite"),
new String("Bite"),
new String("Extrasensory"),
new String("Extrasensory"),
new String("Confusion")

};
}

  static {
    Moveset_OffsensiveMoves2 = new String[] {
new String("null"),
new String("Power Whip"),
new String("Solar Beam"),
new String("Solar Beam"),
new String("Flamethrower"),
new String("Flamethrower"),
new String("Overheat"),
new String("Aqua Tail"),
new String("Hydro Pump"),
new String("Hydro Pump"),
new String("Struggle"),
new String("Struggle"),
new String("Bug Buzz"),
new String("Struggle"),
new String("Struggle"),
new String("Sludge Bomb"),
new String("Aerial Ace"),
new String("Aerial Ace"),
new String("Hurricane"),
new String("Hyper Fang"),
new String("Hyper Beam"),
new String("Sky Attack"),
new String("Sky Attack"),
new String("Sludge Bomb"),
new String("Gunk Shot"),
new String("Wild Charge"),
new String("Wild Charge"),
new String("Dig"),
new String("Earthquake"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Earthquake"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Earthquake"),
new String("Moonblast"),
new String("Dazzling Gleam"),
new String("Flamethrower"),
new String("Overheat"),
new String("Dazzling Gleam"),
new String("Hyper Bem"),
new String("Air Cutter"),
new String("Shadow Ball"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Solar Beam"),
new String("Seed Bomb"),
new String("Solar Beam"),
new String("Signal Beam"),
new String("Bug Buzz"),
new String("Dig"),
new String("Earthquake"),
new String("Foul Play"),
new String("Play Rough"),
new String("Aqua Tail"),
new String("Hydro Pump"),
new String("Cross Chop"),
new String("Close Combat"),
new String("Flamethrower"),
new String("Fire Blast"),
new String("Bubble Beam"),
new String("Bubble Beam"),
new String("Dynamic Punch"),
new String("Shadow Ball"),
new String("Shadow Ball"),
new String("Future Sight"),
new String("Cross Chop"),
new String("Dynamic Punch"),
new String("Dynamic Punch"),
new String("Power Whip"),
new String("Power Whip"),
new String("Solar Beam"),
new String("Bubble Beam"),
new String("Hydro Pump"),
new String("Rock Slide"),
new String("Stone Edge"),
new String("Stone Edge"),
new String("Flame Charge"),
new String("Fire Blast"),
new String("Psychock"),
new String("Psychic"),
new String("Thunder Bolt"),
new String("Zap Cannon"),
new String("Leaf Blade"),
new String("Brave Bird"),
new String("Drill Peck"),
new String("Aqua Tail"),
new String("Blizzard"),
new String("Sludge Bomb"),
new String("Gunk Shot"),
new String("Water Pulse"),
new String("Avalanche"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Shadow Ball"),
new String("Stone Edge"),
new String("Psychic"),
new String("Future Sight"),
new String("Bubble Beam"),
new String("Water Pulse"),
new String("Thunderbolt"),
new String("Thunderbolt"),
new String("Psychic"),
new String("Solar Beam"),
new String("Dig"),
new String("Earthquake"),
new String("Close Combat"),
new String("Close Combat"),
new String("Hyper Beam"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Bulldoze"),
new String("Earthquake"),
new String("Hyper Beam"),
new String("Solar Beam"),
new String("Outrage"),
new String("Bubble Beam"),
new String("Hydro Pump"),
new String("Aqua Tail"),
new String("Ice Beam"),
new String("Bubble Beam"),
new String("Hydro Pump"),
new String("Psychic"),
new String("X-Scissor"),
new String("Avalanche"),
new String("Thunderbolt"),
new String("Fire Blast"),
new String("X-Scissor"),
new String("Earthquake"),
new String("Struggle"),
new String("Hydro Pump"),
new String("Blizzard"),
new String("Swift"),
new String("Hydro Pump"),
new String("Thunderbolt"),
new String("Overheat"),
new String("Hyper Beam"),
new String("Ancient Power"),
new String("Ancient Power"),
new String("Ancient Power"),
new String("Stone Edge"),
new String("Hyper Beam"),
new String("Hyper Beam"),
new String("Aqua Tail"),
new String("Dragon Pulse"),
new String("Outrage"),
new String("Grass Knot"),
new String("Grass Knot"),
new String("Solar Beam"),
new String("Flamethrower"),
new String("Flamethrower"),
new String("Overheat"),
new String("Water Pulse"),
new String("Water Pulse"),
new String("Hydro Pump"),
new String("Grass Knot"),
new String("Hyper Beam"),
new String("Sky Attack"),
new String("Sky Attack"),
new String("Aerial Ace"),
new String("Bug Buzz"),
new String("Signal Beam"),
new String("Megahorn"),
new String("Sludge Bomb"),
new String("Thunderbolt"),
new String("Hydro Pump"),
new String("Thunderbolt"),
new String("Grass Knot"),
new String("Shadow Ball"),
new String("Dazzling Gleam"),
new String("Dazzling Gleam"),
new String("Drill Peck"),
new String("Future Sight"),
new String("Thunderbolt"),
new String("Thunderbolt"),
new String("Zap Cannon"),
new String("Leaf Blade"),
new String("Aqua Tail"),
new String("Play Rough"),
new String("Stone Edge"),
new String("Hydro Pump"),
new String("Grass Knot"),
new String("Grass Knot"),
new String("Solar Beam"),
new String("Swift"),
new String("Grass Knot"),
new String("Solar Beam"),
new String("Aerial Ace"),
new String("Dig"),
new String("Earthquake"),
new String("Future Sight"),
new String("Foul Play"),
new String("Foul Play"),
new String("Psychic"),
new String("Ominous Wind"),
new String("Struggle"),
new String("Mirror Coat"),
new String("Psychic"),
new String("Gyro Ball"),
new String("Heavy Slam"),
new String("Rock Slide"),
new String("Dig"),
new String("Heavy Slam"),
new String("Dazzling Gleam"),
new String("Play Rough"),
new String("Sludge Wave"),
new String("Iron Head"),
new String("Stone Edge"),
new String("Close Combat"),
new String("Avalanche"),
new String("Play Rough"),
new String("Hyper Beam"),
new String("Flame Burst"),
new String("Overheat"),
new String("Rock Slide"),
new String("Avalanche"),
new String("Power Gem"),
new String("Water Pulse"),
new String("Gunk Shot"),
new String("Ice Punch"),
new String("Aerial Ace"),
new String("Sky Attack"),
new String("Flamethrower"),
new String("Foul Play"),
new String("Outrage"),
new String("Bulldoze"),
new String("Earthquake"),
new String("Hyper Beam"),
new String("Wild Charge"),
new String("Struggle"),
new String("Rock Slide"),
new String("Close Combat"),
new String("Ice Beam"),
new String("Discharge"),
new String("Flame Burst"),
new String("Stomp"),
new String("Hyper Beam"),
new String("Wild Charge"),
new String("Overheat"),
new String("Hydro Pump"),
new String("Ancient Power"),
new String("Dig"),
new String("Stone Edge"),
new String("Future Sight"),
new String("Fire Blast"),
new String("Psychic")

};
}

  static {
    Moveset_DefensiveMoves1 = new String[] {
new String("null"),
new String("Vine Whip"),
new String("Razor Leaf"),
new String("Razor Leaf"),
new String("Ember"),
new String("Ember"),
new String("Fire Spin"),
new String("Bubble"),
new String("Water Gun"),
new String("Water Gun"),
new String("Bug Bite"),
new String("Bug Bite"),
new String("Confusion"),
new String("Bug Bite"),
new String("Bug Bite"),
new String("Infestation"),
new String("Quick Attack"),
new String("Wing Attack"),
new String("Air Slash"),
new String("Quick Attack"),
new String("Quick Attack"),
new String("Peck"),
new String("Peck"),
new String("Acid"),
new String("Acid"),
new String("Quick Attack"),
new String("Mud Shot"),
new String("Mud Shot"),
new String("Metal Claw"),
new String("Poison Sting"),
new String("Poison Sting"),
new String("Poison Jab"),
new String("Peck"),
new String("Poison Jab"),
new String("Iron Tail"),
new String("Zen Headbutt"),
new String("Charge Beam"),
new String("Ember"),
new String("Fire Spin"),
new String("Feint Attack"),
new String("Feint Attack"),
new String("Quick Attack"),
new String("Wing Attack"),
new String("Razor Leaf"),
new String("Razor Leaf"),
new String("Razor Leaf"),
new String("Bug Bite"),
new String("Struggle Bug"),
new String("Confusion"),
new String("Confusion"),
new String("Mud Slap"),
new String("Mud Slap"),
new String("Scratch"),
new String("Feint Attack"),
new String("Zen Headbutt"),
new String("Confusion"),
new String("Karate Chop"),
new String("Counter"),
new String("Ember"),
new String("Snarl"),
new String("Bubble"),
new String("Bubble"),
new String("Bubble"),
new String("Charge Beam"),
new String("Confusion"),
new String("Confusion"),
new String("Rock Smash"),
new String("Karate Chop"),
new String("Counter"),
new String("Acid"),
new String("Bullet Seed"),
new String("Razor Leaf"),
new String("Bubble"),
new String("Poison Jab"),
new String("Rock Throw"),
new String("Rock Throw"),
new String("Mud Slap"),
new String("Ember"),
new String("Fire Spin"),
new String("Confusion"),
new String("Confusion"),
new String("Spark"),
new String("Charge Beam"),
new String("Air Slash"),
new String("Peck"),
new String("Feint Attack"),
new String("Ice Shard"),
new String("Iron Tail"),
new String("Mud Slap"),
new String("Infestation"),
new String("Ice Shard"),
new String("Ice Shard"),
new String("Astonish"),
new String("Astonish"),
new String("Hex"),
new String("Rock Throw"),
new String("Confusion"),
new String("Confusion"),
new String("Bubble"),
new String("Bubble"),
new String("Spark"),
new String("Volt Switch"),
new String("Confusion"),
new String("Extrasensory"),
new String("Mud Slap"),
new String("Mud Slap"),
new String("Rock Smash"),
new String("Counter"),
new String("Zen Headbutt"),
new String("Infestation"),
new String("Infestation"),
new String("Mud Slap"),
new String("Mud Slap"),
new String("Zen Headbutt"),
new String("Infestation"),
new String("Mud Slap"),
new String("Bubble"),
new String("Water Gun"),
new String("Peck"),
new String("Peck"),
new String("Water Gun"),
new String("Hidden Power"),
new String("Confusion"),
new String("Air Slash"),
new String("Confusion"),
new String("Thunder Shock"),
new String("Ember"),
new String("Rock Smash"),
new String("Zen Headbutt"),
new String("Splash"),
new String("Dragon Tail"),
new String("Frost Breath"),
new String("Quick Attack"),
new String("Water Gun"),
new String("Volt Switch"),
new String("Fire Spin"),
new String("Hidden Power"),
new String("Mud Shot"),
new String("Mud Shot"),
new String("Mud Shot"),
new String("Rock Smash"),
new String("Steel Wing"),
new String("Zen Headbutt"),
new String("Iron Tail"),
new String("Iron Tail"),
new String("Dragon Tail"),
new String("Vine Whip"),
new String("Razor Leaf"),
new String("Razor Leaf"),
new String("Ember"),
new String("Ember"),
new String("Ember"),
new String("Water Gun"),
new String("Water Gun"),
new String("Water Gun"),
new String("Quick Attack"),
new String("Quick Attack"),
new String("Peck"),
new String("Extrasensory"),
new String("Bug Bite"),
new String("Struggle Bug"),
new String("Bug Bite"),
new String("Infestation"),
new String("Air Slash"),
new String("Bubble"),
new String("Charge Beam"),
new String("Thunder Shock"),
new String("Zen Headbutt"),
new String("Feint Attack"),
new String("Hidden Power"),
new String("Hidden Power"),
new String("Peck"),
new String("Air Slash"),
new String("Thunder Shock"),
new String("Charge Beam"),
new String("Volt Switch"),
new String("Razor Leaf"),
new String("Bubble"),
new String("Bubble"),
new String("Rock Throw"),
new String("Bubble"),
new String("Bullet Seed"),
new String("Bullet Seed"),
new String("Infestation"),
new String("Astonish"),
new String("Razor Leaf"),
new String("Bullet Seed"),
new String("Quick Attack"),
new String("Mud Shot"),
new String("Mud Shot"),
new String("Confusion"),
new String("Snarl"),
new String("Peck"),
new String("Confusion"),
new String("Hex"),
new String("Hidden Power"),
new String("Counter"),
new String("Confusion"),
new String("Bug Bite"),
new String("Struggle Bug"),
new String("Astonish"),
new String("Wing Attack"),
new String("Iron Tail"),
new String("Tackle"),
new String("Snarl"),
new String("Poison Sting"),
new String("Bullet Punch"),
new String("Struggle"),
new String("Struggle Bug"),
new String("Ice Shard"),
new String("Scratch"),
new String("Counter"),
new String("Ember"),
new String("Rock Throw"),
new String("Powder Snow"),
new String("Powder Snow"),
new String("Bubble"),
new String("Mud Shot"),
new String("Mud Shot"),
new String("Ice Shard"),
new String("Bubble"),
new String("Air Slash"),
new String("Feint Attack"),
new String("Snarl"),
new String("Water Gun"),
new String("Rock Smash"),
new String("Counter"),
new String("Hidden Power"),
new String("Zen Headbutt"),
new String("Tackle"),
new String("Rock Smash"),
new String("Rock Smash"),
new String("Powder Snow"),
new String("Thunder Shock"),
new String("Ember"),
new String("Zen Headbutt"),
new String("Zen Headbutt"),
new String("Volt Switch"),
new String("Fire Spin"),
new String("Extrasensory"),
new String("Rock Smash"),
new String("Rock Smash"),
new String("Iron Tail"),
new String("Extrasensory"),
new String("Extrasensory"),
new String("Confusion")

};
}

  static {
    Moveset_DefensiveMoves2 = new String[] {
new String("null"),
new String("Sludge Bomb"),
new String("Solar Beam"),
new String("Solar Beam"),
new String("Flame Charge"),
new String("Fire Punch"),
new String("Overheat"),
new String("Aqua Tail"),
new String("Ice Beam"),
new String("Ice Beam"),
new String("Struggle"),
new String("Struggle"),
new String("Bug Buzz"),
new String("Struggle"),
new String("Struggle"),
new String("Sludge Bomb"),
new String("Aerial Ace"),
new String("Aerial Ace"),
new String("Aerial Ace"),
new String("Hyper Fang"),
new String("Hyper Beam"),
new String("Drill Peck"),
new String("Aerial Ace"),
new String("Sludge Bomb"),
new String("Gunk Shot"),
new String("Wild Charge"),
new String("Wild Charge"),
new String("Dig"),
new String("Bulldoze"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Earthquake"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Earthquake"),
new String("Disarming Voice"),
new String("Dazzling Gleam"),
new String("Flame Charge"),
new String("Overheat"),
new String("Dazzling Gleam"),
new String("Play Rough"),
new String("Air Cutter"),
new String("Shadow Ball"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Solar Beam"),
new String("Seed Bomb"),
new String("Solar Beam"),
new String("Signal Beam"),
new String("Bug Buzz"),
new String("Dig"),
new String("Earthquake"),
new String("Night Slash"),
new String("Play Rough"),
new String("Aqua Tail"),
new String("Hydro Pump"),
new String("Cross Chop"),
new String("Close Combat"),
new String("Flamethrower"),
new String("Fire Blast"),
new String("Bubble Beam"),
new String("Water Pulse"),
new String("Dynamic Punch"),
new String("Psyshock"),
new String("Shadow Ball"),
new String("Shadow Ball"),
new String("Cross Chop"),
new String("Dynamic Punch"),
new String("Dynamic Punch"),
new String("Power Whip"),
new String("Power Whip"),
new String("Solar Beam"),
new String("Water Pulse"),
new String("Hydro Pump"),
new String("Dig"),
new String("Rock Slide"),
new String("Dig"),
new String("Flame Charge"),
new String("Fire Blast"),
new String("Psychock"),
new String("Ice Beam"),
new String("Magnet Bomb"),
new String("Magnet Bomb"),
new String("Leaf Blade"),
new String("Drill Peck"),
new String("Drill Peck"),
new String("Aqua Tail"),
new String("Blizzard"),
new String("Sludge Bomb"),
new String("Gunk Shot"),
new String("Water Pulse"),
new String("Avalanche"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Shadow Ball"),
new String("Sand Tomb"),
new String("Psyshock"),
new String("Future Sight"),
new String("Water Pulse"),
new String("Water Pulse"),
new String("Discharge"),
new String("Thunderbolt"),
new String("Seed Bomb"),
new String("Solar Beam"),
new String("Dig"),
new String("Dig"),
new String("Close Combat"),
new String("Close Combat"),
new String("Power Whip"),
new String("Sludge Bomb"),
new String("Sludge Bomb"),
new String("Bulldoze"),
new String("Earthquake"),
new String("Dazzling Gleam"),
new String("Solar Beam"),
new String("Outrage"),
new String("Dragon Pulse"),
new String("Dragon Pulse"),
new String("Aqua Tail"),
new String("Ice Beam"),
new String("Bubble Beam"),
new String("Hydro Pump"),
new String("Shadow Ball"),
new String("Aerial Ace"),
new String("Avalanche"),
new String("Thunderbolt"),
new String("Fire Blast"),
new String("X-Scissor"),
new String("Horn Attack"),
new String("Struggle"),
new String("Outrage"),
new String("Ice Beam"),
new String("Dig"),
new String("Aqua Tail"),
new String("Thunderbolt"),
new String("Overheat"),
new String("Hyper Beam"),
new String("Ancient Power"),
new String("Ancient Power"),
new String("Ancient Power"),
new String("Ancient Power"),
new String("Ancient Power"),
new String("Hyper Beam"),
new String("Wrap"),
new String("Dragon Pulse"),
new String("Outrage"),
new String("Grass Knot"),
new String("Grass Knot"),
new String("Solar Beam"),
new String("Flame Charge"),
new String("Flame Charge"),
new String("Overheat"),
new String("Crunch"),
new String("Crunch"),
new String("Ice Beam"),
new String("Dig"),
new String("Hyper Beam"),
new String("Aerial Ace"),
new String("Sky Attack"),
new String("Silver Wind"),
new String("Bug Buz"),
new String("Signal Beam"),
new String("Cross Poison"),
new String("Sludge Bomb"),
new String("Thunderbolt"),
new String("Thunderbolt"),
new String("Thunderbolt"),
new String("Grass Knot"),
new String("Shadow Ball"),
new String("Dazzling Gleam"),
new String("Dazzling Gleam"),
new String("Psyshock"),
new String("Aerial Ace"),
new String("Thunderbolt"),
new String("Discharge"),
new String("Zap Cannon"),
new String("Leaf Blade"),
new String("Aqua Tail"),
new String("Play Rough"),
new String("Rock Slide"),
new String("Hydro Pump"),
new String("Grass Knot"),
new String("Grass Knot"),
new String("Solar Beam"),
new String("Swift"),
new String("Grass Knot"),
new String("Solar Beam"),
new String("Silver Wind"),
new String("Dig"),
new String("Sludge Bomb"),
new String("Future Sight"),
new String("Foul Play"),
new String("Drill Peck"),
new String("Fire Blast"),
new String("Ominous Wind"),
new String("Struggle"),
new String("Mirror Coat"),
new String("Thunder Bolt"),
new String("Gyro Ball"),
new String("Heavy Slam"),
new String("Dig"),
new String("Dig"),
new String("Earthquake"),
new String("Dazzling Gleam"),
new String("Play Rough"),
new String("Aqua Tail"),
new String("Iron Head"),
new String("Rock Blast"),
new String("Close Combat"),
new String("Avalanche"),
new String("Crunch"),
new String("Hyper Beam"),
new String("Flame Burst"),
new String("Overheat"),
new String("Icy Wind"),
new String("Avalanche"),
new String("Power Gum"),
new String("Water Pulse"),
new String("Water Pulse"),
new String("Aerial Ace"),
new String("Ice Shard"),
new String("Sky Attack"),
new String("Crunch"),
new String("Fire Blast"),
new String("Outrage"),
new String("Bulldoze"),
new String("Play Rough"),
new String("Hyper Beam"),
new String("Wild Charge"),
new String("Struggle"),
new String("Rock Slide"),
new String("Close Combat"),
new String("Psyshock"),
new String("Discharge"),
new String("Fire Punch"),
new String("Body Slam"),
new String("Dazzling Gleam"),
new String("Wild Charge"),
new String("Overheat"),
new String("Hydro Pump"),
new String("Ancient Power"),
new String("Dig"),
new String("Crunch"),
new String("Sky Attack"),
new String("Fire Blast"),
new String("Dazzling Gleam")

};
}






  public static Boolean isBestOffensiveMoveset(final Pokemon p) 
  {
  String Move1 = PokemonUtils.formatMove(p.getMove1());
  String Move2 = PokemonUtils.formatMove(p.getMove2());


//  System.out.println("Move1: " + Move1 + " Move2: " + Move2 );

  for( int i = 0; i < Moveset_PokemonNames.length; i++ )
  {
   //System.out.println("i: " + i + " Moveset_PokemonNames: " + Moveset_PokemonNames[i] + " getLocalPokeName: " + PokemonUtils.getLocalPokeName(p) );

      if( Moveset_PokemonNames[i].equals(PokemonUtils.getLocalPokeName(p)))
	  {
	    //System.out.println("Move1: " + Move1 + " Move2: " + Move2 );
	  //System.out.println(" FOUND" + " Moveset_OffsensiveMoves1[i]: " + Moveset_OffsensiveMoves1[i] + " Moveset_OffsensiveMoves2[i]: " + Moveset_OffsensiveMoves2[i] );

	      if( ( Move1.equals(Moveset_OffsensiveMoves1[i]) ) && ( Move2.equals(Moveset_OffsensiveMoves2[i]) ) )
		  {
		  	  return true;
		  }

	  }
  
  }


return false;
  }


  public static Boolean isBestDefensiveMoveset(final Pokemon p) 
  {
    String Move1 = PokemonUtils.formatMove(p.getMove1());
  String Move2 = PokemonUtils.formatMove(p.getMove2());

    for( int i = 0; i < Moveset_PokemonNames.length; i++ )
  {
      if( Moveset_PokemonNames[i].equals(PokemonUtils.getLocalPokeName(p)))
	  {
	      if( ( Move1.equals(Moveset_DefensiveMoves1[i]) ) && ( Move2.equals(Moveset_DefensiveMoves2[i]) ) )
		  {
		  	  return true;
		  }

	  }
  
  }


return false;

  }





}



